# Generated by Django 4.2.4 on 2023-08-18 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shot_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_make', models.BooleanField()),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.games')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.players')),
            ],
        ),
        migrations.CreateModel(
            name='Player_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starter', models.BooleanField(default=True)),
                ('minutes', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('offensive_rebounds', models.IntegerField(default=0)),
                ('defensive_rebounds', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('turnovers', models.IntegerField(default=0)),
                ('defensive_fouls', models.IntegerField(default=0)),
                ('offensive_fouls', models.IntegerField(default=0)),
                ('free_throws_made', models.IntegerField(default=0)),
                ('free_throws_attempted', models.IntegerField(default=0)),
                ('two_pointers_made', models.IntegerField(default=0)),
                ('two_pointers_attempted', models.IntegerField(default=0)),
                ('three_pointers_made', models.IntegerField(default=0)),
                ('three_pointers_attempted', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.games')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.players')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teams')),
            ],
        ),
    ]
