# Generated by Django 4.2.4 on 2023-08-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='player_stats',
            constraint=models.UniqueConstraint(fields=('game', 'player'), name='unique_migration_host_combination'),
        ),
    ]
