# Generated by Django 4.2.4 on 2023-08-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_player_stats_unique_migration_host_combination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shot_data',
            name='id',
        ),
        migrations.AddField(
            model_name='shot_data',
            name='shot_data_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
